package main

var fileNames = []string{
	"401K Report",
	"new user password",
	"password test",
	"90 Day Admin password",
	"Accounts and Passwords",
	"Accounts Passwords",
	"All win passwords",
	"Bank Wire Details",
	"carrier websites and passwords",
	"Cashflow",
	"Computer Passwords",
	"Contact List and Passwords",
	"credentialspassword",
	"Customer Phone List",
	"Database Passwords",
	"datacenter userids and passwords",
	"department password list",
	"Digital User Name and passwords",
	"Employee Termination List",
	"Excel Passwords",
	"Facebook Password Info",
	"Family Online Accounts & Passwords",
	"FTP LOGIN PASSWORD SHEET",
	"FTP_passwords",
	"group password list",
	"Hold Codes- Passwords",
	"ID for Employee & Contractor.xls",
	"Important Passwords",
	"Internal Audit Results",
	"IP and Password",
	"IT Invoice Statement.xlsx",
	"IT Security Vulnerabilities",
	"Login & Password",
	"Login and Passwords",
	"Login_Password_Conne",
	"Logins and Passwords",
	"Mail Master Password List",
	"Marketing Password",
	"Master Application and Password List",
	"Master Intern Password List",
	"Master Inventory",
	"Master_Password_Sheet",
	"MASTERS - User List NO PASSWORDS",
	"McAfeepassword",
	"MerchandisingSetup - ID and Password info",
	"My Passwords",
	"NETWORK A R REPORT PASSWORD",
	"New Customer Checklist- Website, Login and Pass",
	"New password to access DOC server",
	"Notification password_userid",
	"Online Passwords",
	"Passports",
	"Password History_09132007",
	"PASSWORD INFO",
	"Password log",
	"Password_Login_English_102208",
	"Passwords (Autosaved)",
	"Passwords to change",
	"Passwords1",
	"PAY-FINAL",
	"Payroll Current",
	"payroll password email",
	"PIN Codes",
	"radhat passwords",
	"Regular Earnings",
	"remote_users_and_passwords",
	"Security and Password Settings",
	"Server Privileged Access",
	"Social Password Log",
	"splunk user pwd",
	"Systems userids and passwords",
	"Unix Keepass Access Certificate",
	"Unix Server Privileged Account Access",
	"Unlock ID and reset password",
	"User ID and Password memo",
	"UserNames&Passwords",
	"wages accountant",
	"website passwords",
	"YouTube login passwords",
}

var awsFileNames = []string{
	"credentials",
	"aws_creds",
	"aws_root",
	"auth_keys",
}
